### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by kramer65** [NeuralSpaz/ti-ina219#1]
I'd love to use this library, but I'm unsure how to use it. It would be great if you could provide a short example in the readme.. :-)

**Comment by NeuralSpaz** [comment]
Hi, I rewrote this as device for [https://periph.io/](url) 
you can find here [https://godoc.org/periph.io/x/periph/experimental/devices/ina219](url)

It is much better documented and supported there with an example code.

but I can also give you some example code for this if you do not want to bring in periph into your code?

**Comment by NeuralSpaz** [comment]
Example
```go
package main

import (
	"fmt"
	"log"
	"time"

	ina219 "github.com/NeuralSpaz/ti-ina219"
)

func main() {
	// Create new sensor with an address of 0x41 and on i2c bus 1.
	Sensor1 := ina219.New(0x41, 1)
	for {
		select {
		case <-time.After(time.Second * 1):
			if err := ina219.Fetch(Sensor1); err != nil {
				log.Println(err)
			}
			fmt.Println(Sensor1)
		}
	}
}
```
